### ISSUE TITLE
视频播放组件有什么好的推荐吗？

### ISSUE THREAD

**Issue by songxiaoliang** [wtus/flutter_kaiyan#6]
视频播放组件有什么好的推荐吗？

**Comment by wtus** [comment]
这个demo没有涉及，我知道的有chewie，但是不太好用，可以试试与原生交互

**Comment by songxiaoliang** [comment]
@wtus 嗯，感谢

**Comment by tengxb** [comment]
> @wtus 嗯，感谢

兄台，视频播放问题解决了吗？求赐教。
视频缓存，以及播放本地视频
